[Log]
level = 'info' # change this to 'debug' if you want to see more detail in the logs

[Recipe]
projectId = '' # FILL IN WITH YOUR WATSONX.AI PROJECT ID
serviceUrl = 'https://us-south.ml.cloud.ibm.com' # change this if your watsonx.ai instance is in a different region
serviceVersion = '2024-05-31'
useNeoPixelLED = false     # set to true if using a NeoPixel LED
useCommonAnodeLED = false  # set to true if using a Common Anode LED

# advanced configuration: you can change the LLM model & parameters here
modelId = 'meta-llama/llama-3-70b-instruct'
version = '2023-05-29'
modelDecodingMethod = 'greedy'
modelMaxNewTokens = 200
modelMinNewTokens = 0
modelStopSequences = ['.']
modelRepetitionPenalty = 1

[Speak]
voice = 'en-US_MichaelV3Voice'
device = 'plughw:0,0' # plugged-in USB card 0, device 0

[Listen]
device = 'plughw:2,0'
backgroundAudioSuppression = 0.6
microphoneRate = 44100
microphoneChannels = 2