[Recipe]
projectId = '' # FILL IN WITH YOUR WATSONX.AI PROJECT ID
serviceUrl = 'https://us-south.ml.cloud.ibm.com' # CHANGE THIS IF YOUR SERVICEURL IS IN A DIFFERENT REGION
serviceVersion = '2024-05-31'
useNeoPixelLED = false     # set to true if using a NeoPixel LED
useCommonAnodeLED = false  # set to true if using a Common Anode LED

# advanced configuration: you can change the LLM model & parameters here
# see https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-model-parameters.html?context=wx&audience=wdp
# for more information on model parameters
modelId = 'ibm/granite-13b-chat-v2'
version = '2023-05-29'
modelDecodingMethod = 'greedy' # options are 'greedy' or 'sample'
modelTemperature = 0.7
modelRandomSeed = 42
modelMinNewTokens = 0
modelMaxNewTokens = 200
modelStopSequences = ['.']
modelRepetitionPenalty = 1.0

[Log]
level = 'info' # change this to 'verbose' or 'debug' to see more detail in the logs

[Listen]
# use `arecord -l` to list audio input devices
device = 'plughw:2,0' # plugged-in USB card 2, device 0
backgroundAudioSuppression = 0.6
microphoneRate = 44100
microphoneChannels = 2

[Shine.NeoPixel]
# On Raspberry Pi 5 models, we use the Serial Peripheral Interface (SPI)
# to communicate with the NeoPixel LED. For GPIO10 (physical pin 19), this
# interface is exposed in the filesystem as /dev/spidev0.0. If your LED
# is connected to a different PIN, you may need to change the SPI interface.
spiInterface = "/dev/spidev0.0"

# On all other Raspberry Pi models, NeoPixels must be connected to one of these
# GPIO pins to work: GPIO10, GPIO12, GPIO18, GPIO21.
#
# GPIO18 is the standard pin, but sound must be disabled to use GPIO18.
#
# To disable sound, edit /boot/config.txt and change:
#   dtparam=audio=on
# to:
#   dtparam=audio=off
# and then reboot.
#
# See https://pinout.xyz for a complete listing of RPi pins.
# See https://learn.adafruit.com/neopixels-on-raspberry-pi/raspberry-pi-wiring
# for more information about using NeoPixels with RPi.
gpioPin = 18 # GPIO18 / Physical pin 12

[Shine.CommonAnode]
redPin = 19   # GPIO19 / Physical pin 35
greenPin = 13 # GPIO13 / Physical pin 33
bluePin = 12  # GPIO12 / Physical pin 32

[Speak]
# use `aplay -l` to list audio output devices
device = 'plughw:0,0' # plugged-in USB card 0, device 0

# see https://cloud.ibm.com/docs/text-to-speech?topic=text-to-speech-voices for available voices
voice = 'en-US_MichaelV3Voice'
