/**
 * Copyright 2016 IBM Corp. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
/************************************************************************
 * Build a talking robot with Watson. 
 * This module uses Watson Speech to Text, Watson Conversation, and Watson Text to Speech.
 * To run: node conversation.js

 * Follow the instructions in XXX to 
 * get the system ready to run this code.
 */

var watson = require('watson-developer-cloud'); //to connect to Watson developer cloud
var config = require("./config.js") // to get our credentials and the attention word from the config.js files
var exec = require('child_process').exec;
var fs = require('fs');
var con;
var attentionWord = config.attentionWord; //you can change the attention word in the config file

/************************************************************************
 * Step #1: Configuring your Bluemix Credentials
 ************************************************************************
 In this step we will be configuring the Bluemix Credentials for Speech to Text, Watson Conversation
 and Text to Speech services.
 */

var speech_to_text = watson.speech_to_text({
    username: config.STTUsername,
    password: config.STTPassword,
    version: 'v1'
});

var conversation = watson.conversation({
    username: config.ConUsername,
    password: config.ConPassword,
    version: 'v1',
    version_date: '2016-07-11'
});

var text_to_speech = watson.text_to_speech({
    username: config.TTSUsername,
    password: config.TTSPassword,
    version: 'v1'
});

/************************************************************************
 * Step #2: Configuring the Microphone
 ************************************************************************
 In this step, we configure your microphone to collect the audio samples as you talk.
 See https://www.npmjs.com/package/mic for more information on
 microphone input events e.g on error, startcomplete, pause, stopcomplete etc.
*/

// Initiate Microphone Instance to Get audio samples
var mic = require('mic');
var micInstance = mic({ 'rate': '44100', 'channels': '2', 'debug': false, 'exitOnSilence': 6 });
var micInputStream = micInstance.getAudioStream();

micInputStream.on('data', function(data) {
    //console.log("Recieved Input Stream: " + data.length);
});

micInputStream.on('error', function(err) {
    console.log("Error in Input Stream: " + err);
});

micInputStream.on('silence', function() {
    // detect silence.
});
micInstance.start();
console.log("TJ is listening, you may speak now.");

var textStream ;

/************************************************************************
 * Step #3: Converting your Speech Commands to Text
 ************************************************************************
 In this step, the audio sample is sent (piped) to "Watson Speech to Text" to transcribe.
 The service converts the audio to text and saves the returned text in "textStream"
*/

textStream = micInputStream.pipe(speech_to_text.createRecognizeStream({
    content_type: 'audio/l16; rate=44100; channels=2',
    interim_results: true,
    keywords: [attentionWord],
    smart_formatting: 'true',
    keywords_threshold: 0.5
  }));

textStream.setEncoding('utf8');

/*********************************************************************
 * Step #4: Parsing the Text and create a response
 *********************************************************************
 In this step, we parse the text to look for attention word and send that sentence
 to watson conversation to get appropriate response. You can change it to something else if needed.
 Once the attention word is detected,the text is sent to Watson conversation for processing. The response is generated by Watson Conversation and is sent back to the module. 
*/

textStream.setEncoding('utf8');
textStream.on('data', function(str) {
    console.log(' ===== Speech to Text ===== : ' + str); // print the text once received
    
    if (str.toLowerCase().indexOf(attentionWord.toLowerCase()) >= 0) {
        var res = str.toLowerCase().replace(attentionWord.toLowerCase(), "");
        console.log("msg sent to conversation:" ,res);
        conversation.message({
            workspace_id: config.ConWorkspace,
            input: {'text': res},
        },  function(err, response) {
            if (err) {
                console.log('error:', err);
            } else {
                con = response.output.text[0];
            }
            
            var params = {
                text: response.output.text[0],
                voice: config.voice,
                accept: 'audio/wav'
            };
            console.log("Result from conversation:" ,con);
            
/*********************************************************************
 Step #5: Speak out the response
 *********************************************************************
 In this step, we text is sent out to Watsons Text to Speech service and result is piped to wave file.
 Wave files are then played using alsa (native audio) tool.
*/
            tempStream = text_to_speech.synthesize(params).pipe(fs.createWriteStream('output.wav')).on('close', function() {
                var create_audio = exec('aplay output.wav', function (error, stdout, stderr) {
                    if (error !== null) {
                        console.log('exec error: ' + error);
                    }
                });
            });
        })
    } else {
        console.log("Waiting to hear", attentionWord);
    }
});

textStream.on('error', function(err) {
    console.log(' ===== An Error has occurred ===== \nYou may have exceeded your payload quota.\n ' + err + "\n Press <ctrl>+C to exit.") ; // handle errors
});
